### ISSUE TITLE
Nested plugins using HauteCouture

### ISSUE THREAD

**Issue by samueljoli** [hapipal/discuss#2]
I'm currently working on a project that is intended to be written as a monolith, but in such a way that when I need to split it up I can do so effortlessly. Here is an example of a service that is mainly a crud api, but nested within it is a web worker that periodically does something.

Imagine this directory tree:
```bash
├── README.md
├── knexfile.js
├── lib
│   ├── core-plugins
│   │   ├── index.js
│   │   └── my-web-worker
│   │       ├── index.js
│   │       ├── package.json
│   │       ├── plugin.js
│   │       └── services
│   │           └── indexer
│   │               ├── constants.js
│   │               ├── index.js
│   │               └── script.js
│   ├── index.js
│   ├── migrations
│   ├── models
│   ├── plugins
│   │   ├── schmervice.js
│   │   └── schwifty.js
│   ├── routes
│   │   └── test.js
├── package.json
├── server
│   ├── index.js
│   └── manifest.js
```

inside the root level `lib` directory i've added a haute-couture amendment for the `core-plugins` directory:
```js
'use strict';

module.exports = {
    add: [
        {
            place: 'core-plugins',
            method: 'register',
            list: true,
            recursive: true,
        }
    ]
};
```
`core-plugins` represent plugins that I may extract out into stand alone plugins at some later day.

Here are the file contents found within `my-web-worker`
- `index.js`
```js
'use strict';

const Plugin = require('./plugin');

module.exports = {
    plugin: Plugin,
    options: {}
};
```
- `plugin.js`
```js
'use strict';

const HauteCouture = require('haute-couture');
const Pkg = require('./package.json');

exports.pkg = Pkg;

exports.register = async (server, options) => {

    await HauteCouture.using(__dirname)(server, options);
};
```

As you can see I've added services to `my-web-worker`, but they don't seem to be registered to the main plugin.

I believe that either I
A: rethink my strategy for nested plugin separation, by looking more into hautecouture's amendments
B: Don't use hautecouture for sub plugin registration
C: Rethink my entire sub plugin strategy completely, and see what the community has to say.

**Comment by devinivy** [comment]
Hey, @Samueljoli!  I think this is definitely on the right track, and you should be able to do what you're trying to do.  I would suggest this: don't worry about the special amendment to make `core-plugins/` behave like the `plugins/` folder.  Instead, create a file `lib/plugins/core-plugins.js` and register whatever plugins you need that live within `lib/core-plugins/` right there:
```js
// lib/plugins/core-plugins.js
'use strict';

module.exports = (srv, options) => ({
    plugins: [{ // Notice this is an array, in case you have multiple core plugins to configure here
        plugin: require('../core-plugins/my-web-worker'),
        options: options.worker // Pass-through any relevant options from the main plugin down to the worker plugin
    }]
});
```

However, I usually keep all plugins like this inside `lib/plugins/`.  In that case you would move your worker to `lib/plugins/my-web-worker/` and create a file very similar to the one above:
```js
// lib/plugins/local.js
'use strict';

// Register and configure all local plugins right here

module.exports = (srv, options) => ({
    plugins: [{
        plugin: require('./my-web-worker'),
        options: options.worker // Pass-through any relevant options from the main plugin down to the worker plugin
    }]
});
```

And a final option, if your main plugin doesn't actually _depend_ on your core-plugins but you want to deploy them together for now: rather than registering them inside your main plugin via haute-couture, register them on your deployment by adding plugins to `server/manifest.js`.

Hope this helps!

**Comment by samueljoli** [comment]
Hey! @devinivy. 
>if your main plugin doesn't actually _depend_ on your core-plugins..

Yup this is exactly the case. Adding plugins to my manifest file. Thanks once again!
